### ISSUE TITLE
word_diffs and sentence_diffs table are not published?

### ISSUE THREAD

**Issue by YamenAjjour** [isi-nlp/NewsEdits#1]
I was trying to access the dataset and could not find word_diffs or sentence_diffs in the datasets.
I only have access to the following tables:
doc_level_stats
matched_sentences
split_sentences
diff
entry
entryversion
feed
feedentry

**Comment by alex2awesome** [comment]
yup the naming conventions changed slightly from the paper, please see the notebooks and README — all the data you need to do flexible processing it here!
